// Package clientgen generates a typed Go HTTP client from a service's routes.
// Each route becomes a method whose request and response types are the handler's
// In and Out types, so a caller gets a compile-checked client for another
// service. Path parameters become string arguments.
package clientgen

import (
	"fmt"
	"go/format"
	"regexp"
	"sort"
	"strings"
)

// Route is one route to generate a method for.
type Route struct {
	Method    string
	Path      string
	Operation string
	In        string
	Out       string
	InImport  string
	OutImport string
}

// Generate returns formatted Go source for a client named after service, in
// package pkg. It returns an error if the generated source is not valid Go.
func Generate(pkg, service string, routes []Route) (string, error) {
	imports := map[string]bool{}
	for _, r := range routes {
		if imp := typeImport(r.In, r.InImport); imp != "" {
			imports[imp] = true
		}
		if imp := typeImport(r.Out, r.OutImport); imp != "" {
			imports[imp] = true
		}
	}

	typeName := exportName(service) + "Client"

	var b strings.Builder
	b.WriteString("// Code generated by \"bosun gen client\". DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("import (\n")
	for _, imp := range []string{"bytes", "context", "encoding/json", "fmt", "io", "net/http", "net/url", "strings"} {
		fmt.Fprintf(&b, "\t%q\n", imp)
	}
	if len(imports) > 0 {
		b.WriteString("\n")
		for _, imp := range sortedKeys(imports) {
			fmt.Fprintf(&b, "\t%q\n", imp)
		}
	}
	b.WriteString(")\n\n")

	fmt.Fprintf(&b, "// %s calls the %s service over HTTP.\n", typeName, service)
	fmt.Fprintf(&b, "type %s struct {\n\tBaseURL string\n\tHTTP    *http.Client\n}\n\n", typeName)
	fmt.Fprintf(&b, "// New%s returns a client for the service at baseURL.\n", typeName)
	fmt.Fprintf(&b, "func New%s(baseURL string) *%s {\n\treturn &%s{BaseURL: baseURL, HTTP: http.DefaultClient}\n}\n\n", typeName, typeName, typeName)

	fmt.Fprintf(&b, `func (c *%s) do(ctx context.Context, method, path string, in, out any) error {
	var body io.Reader
	if in != nil {
		raw, err := json.Marshal(in)
		if err != nil {
			return err
		}
		body = bytes.NewReader(raw)
	}
	req, err := http.NewRequestWithContext(ctx, method, strings.TrimRight(c.BaseURL, "/")+path, body)
	if err != nil {
		return err
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	hc := c.HTTP
	if hc == nil {
		hc = http.DefaultClient
	}
	resp, err := hc.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode/100 != 2 {
		b, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
		return fmt.Errorf("%%s %%s: %%s: %%s", method, path, resp.Status, strings.TrimSpace(string(b)))
	}
	if out != nil {
		return json.NewDecoder(resp.Body).Decode(out)
	}
	return nil
}

`, typeName)

	for _, r := range routes {
		writeMethod(&b, typeName, r)
	}

	src := b.String()
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return src, fmt.Errorf("clientgen: generated invalid Go: %w", err)
	}
	return string(formatted), nil
}

var paramRE = regexp.MustCompile(`\{([a-zA-Z_][a-zA-Z0-9_]*)(\.\.\.)?\}`)

func writeMethod(b *strings.Builder, typeName string, r Route) {
	name := methodName(r)
	params := paramRE.FindAllStringSubmatch(r.Path, -1)

	var args []string
	args = append(args, "ctx context.Context")
	for _, p := range params {
		args = append(args, p[1]+" string")
	}
	inExpr := typeExpr(r.In)
	hasIn := inExpr != "struct{}" && inExpr != ""
	if hasIn {
		args = append(args, "in "+inExpr)
	}
	outExpr := typeExpr(r.Out)
	if outExpr == "" {
		outExpr = "struct{}"
	}

	pathExpr := pathExpr(r.Path)
	inArg := "nil"
	if hasIn {
		inArg = "in"
	}

	fmt.Fprintf(b, "func (c *%s) %s(%s) (%s, error) {\n", typeName, name, strings.Join(args, ", "), outExpr)
	if outExpr == "struct{}" {
		fmt.Fprintf(b, "\treturn struct{}{}, c.do(ctx, %q, %s, %s, nil)\n", r.Method, pathExpr, inArg)
	} else {
		fmt.Fprintf(b, "\tvar out %s\n", outExpr)
		fmt.Fprintf(b, "\terr := c.do(ctx, %q, %s, %s, &out)\n", r.Method, pathExpr, inArg)
		b.WriteString("\treturn out, err\n")
	}
	b.WriteString("}\n\n")
}

// pathExpr turns "/users/{id}/posts" into a Go string expression that escapes
// each parameter: `"/users/" + url.PathEscape(id) + "/posts"`.
func pathExpr(path string) string {
	if !strings.Contains(path, "{") {
		return fmt.Sprintf("%q", path)
	}
	var parts []string
	last := 0
	for _, loc := range paramRE.FindAllStringSubmatchIndex(path, -1) {
		if loc[0] > last {
			parts = append(parts, fmt.Sprintf("%q", path[last:loc[0]]))
		}
		name := path[loc[2]:loc[3]]
		parts = append(parts, "url.PathEscape("+name+")")
		last = loc[1]
	}
	if last < len(path) {
		parts = append(parts, fmt.Sprintf("%q", path[last:]))
	}
	return strings.Join(parts, " + ")
}

func methodName(r Route) string {
	// operation looks like "pkg.(*Controller).Method" or "pkg.Method-fm".
	op := r.Operation
	op = strings.TrimSuffix(op, "-fm")
	if i := strings.LastIndex(op, "."); i >= 0 {
		op = op[i+1:]
	}
	if op != "" && isIdent(op) {
		return exportName(op)
	}
	// fallback: Method + last path segment
	seg := strings.Trim(paramRE.ReplaceAllString(r.Path, ""), "/")
	if i := strings.LastIndex(seg, "/"); i >= 0 {
		seg = seg[i+1:]
	}
	return exportName(strings.ToLower(r.Method)) + exportName(seg)
}

// typeExpr normalizes a reflect type string for use in generated code.
func typeExpr(t string) string {
	switch t {
	case "struct {}":
		return "struct{}"
	case "interface {}", "":
		if t == "" {
			return ""
		}
		return "any"
	default:
		return t
	}
}

// typeImport returns the import path for a type, unless the type is a builtin
// or unnamed (no package).
func typeImport(t, imp string) string {
	if imp == "" {
		return ""
	}
	if strings.HasPrefix(t, "struct") || strings.HasPrefix(t, "interface") {
		return ""
	}
	return imp
}

func exportName(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return "Client"
	}
	var b strings.Builder
	upper := true
	for _, r := range s {
		if r == '_' || r == '-' || r == ' ' {
			upper = true
			continue
		}
		if upper {
			b.WriteString(strings.ToUpper(string(r)))
			upper = false
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func isIdent(s string) bool {
	for i, r := range s {
		if r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') {
			continue
		}
		if i > 0 && r >= '0' && r <= '9' {
			continue
		}
		return false
	}
	return s != ""
}

func sortedKeys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
