package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func runGenRegistry(t *testing.T, args ...string) (string, error) {
	t.Helper()
	cmd := genRegistryCmd()
	var stderr bytes.Buffer
	cmd.SetErr(&stderr)
	cmd.SetOut(&stderr)
	cmd.SetArgs(args)
	err := cmd.Execute()
	return stderr.String(), err
}

func TestGenRegistryWriteAndCheck(t *testing.T) {
	dir := t.TempDir()
	files := map[string]string{
		"go.mod":         "module example.com/app\n\ngo 1.22\n",
		"main.go":        "package main\n\nfunc main() {}\n",
		"orders/ctrl.go": "package orders\n\nimport \"github.com/bluebeard63/bosun\"\n\ntype Ctrl struct{}\n\nvar _ = bosun.Controller[Ctrl](\"/orders\")\n",
	}
	for rel, body := range files {
		p := filepath.Join(dir, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	if _, err := runGenRegistry(t, "--dir", dir, "--check"); err == nil {
		t.Fatal("--check should fail before the file exists")
	}
	msg, err := runGenRegistry(t, "--dir", dir)
	if err != nil {
		t.Fatalf("generate: %v (%s)", err, msg)
	}
	src, err := os.ReadFile(filepath.Join(dir, "zz_bosun_registry.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(src), `_ "example.com/app/orders" // Controller[Ctrl]`) ||
		!strings.HasPrefix(string(src), "// Code generated by bosun gen registry. DO NOT EDIT.") {
		t.Fatalf("generated file:\n%s", src)
	}
	if _, err := runGenRegistry(t, "--dir", dir, "--check"); err != nil {
		t.Fatalf("--check after generate: %v", err)
	}

	// Adding a registering package makes the file stale.
	p := filepath.Join(dir, "billing", "svc.go")
	_ = os.MkdirAll(filepath.Dir(p), 0o755)
	_ = os.WriteFile(p, []byte("package billing\n\nimport \"github.com/bluebeard63/bosun\"\n\ntype Svc struct{}\n\nvar _ = bosun.Service[Svc]()\n"), 0o644)
	if _, err := runGenRegistry(t, "--dir", dir, "--check"); err == nil || !strings.Contains(err.Error(), "out of date") {
		t.Fatalf("--check should report stale file, got %v", err)
	}
}
